apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hynhvzrgl-python 
  janus-idp.io/tekton: hynhvzrgl-python
  backstage.io/kubernetes-id: hynhvzrgl-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hynhvzrgl-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml